### ISSUE TITLE
[DÚVIDA] Atualização de Servidores

### ISSUE THREAD

**Issue by guicouto** [nfephp-org/sped-ibpt#20]
Bom dia,
recebi recentemente um e-mail do IBPT, avisando que haverá atualizações nos servidores, tornando obrigatório o uso do protocolo TLS 1.2 em todos as requisições.

A  classe já está preparada para isso, ou necessita fazer algum tipo de modificação.
Caso seja necessário me coloco à disposição.

Segue abaixo um print do e-mail.

![email_ibpt](https://user-images.githubusercontent.com/8810377/41810502-1a73a112-76d6-11e8-861e-c244115a9ba3.png)

**Comment by robmachado** [comment]
Ainda não Guilherme;
A URL atual não usa nenhum protocolo SSL a classe terá de ser ajustada para isso.

**Comment by robmachado** [comment]
Atualizada a versão 2.0 para usar os novos webservices do IBPT
