### ISSUE TITLE
Integração

### ISSUE THREAD

**Issue by uilhianet** [nfephp-org/sped-ibpt#23]
Alguém poderia me dar um dica de como seria a melhor formar de fazer a integração?

**Comment by robmachado** [comment]
É muito simples e está indicado no README como fazer !! mas qual é a sua duvida ??

**Comment by LucasSalicano** [comment]
Boa noite, tenho duvidas referente ao sped-ibpt. o calculo e feito exemplo: (ValorTributoNacional * quantidadeProduto) + as demais tributação.. pois meu total sempre da muito baixo e fico em duvida se esta certo

**Comment by robmachado** [comment]
O sped-ibpt não faz nenhum calculo !!!
Não sei a que você se refere !!

**Comment by JotaVeUltra** [comment]
`use NFePHP\Ibpt\Ibpt;

$token = "<indique seu token>"; //OBRIGATÓRIO
$cnpj = "<indique seu CNPJ>"; //OBRIGATÓRIO

$ncm = "60063210"; //OBRIGATÓRIO coloque o NCM do produto
$uf = 'SP'; //OBRIGATÓRIO coloque o estado que deseja saber os dados
$extarif = 0; //OBRIGATÓRIO indique o numero da exceção tarifaria, se existir ou deixe como zero
$codigoInterno = ''; //(OPCIONAL) indique o codigo interno do produto 
$descricao = 'Tecido';//OBRIGATÓRIO
$unidadeMedida = 'kg'; //OBRIGATÓRIO
$valor = '60.00'; //OBRIGATÓRIO
$gtin = 'SEM GTIN'; //OBRIGATÓRIO

//instancia a classe 
$ibpt = new Ibpt($cnpj, $token);

$resp = $ibpt->productTaxes(
    $uf,
    $ncm,
    $extarif,
    $descricao,
    $unidadeMedida,
    $valor,
    $gtin,
    $codigoInterno
);`

Estou com uma duvida neste exemplo.

A variavel $valor está recebendo o valor antes ou depois de calcular os impostos?
"60.00" é o valor do produto ou é o valor do produto mais os impostos?

**Comment by robmachado** [comment]
vide https://deolhonoimposto.ibpt.org.br/Site/API#!//Produtos_Get
