### ISSUE TITLE
Dúvida: calcular ou usar tabela?

### ISSUE THREAD

**Issue by eumanito** [nfephp-org/sped-ibpt#25]
Pessoal, por que preciso dessa API com valores tabelados ao invés de usar o valor dos tributos calculados?

vTotTrib = vICMS + vICMSST - vICMSDeson + vIPI + vII + vIOF + vCOFINS + vPIS

**Comment by regisnew** [comment]
Opa. Tenho o mesmo interesse. Alguém tem um caminho?
